ActionManager {
 Actions {
  Action TK_OpenCockpit {
   InputSource InputSourceSum "{6E36291872BDD4F4}" {
    Sources {
     InputSourceValue "{0EE4CB8DDBA00BD0}" {
      Input "keyboard:KC_U"
     }
    }
   }
  }
 }
 Contexts {
  ActionContext IngameContext {
   ActionRefs +{
    "TK_OpenCockpit"
   }
  }
  ActionContext TK_CockpitContext {
   Priority 50
   ActionRefs {
    "MenuBack"
    "MenuSelect"
    "ChatToggle"
   }
  }
 }
}
