SCR_MissionHeader {
 World "{A4F3C930AC6F7950}worlds/Arland/KlondikeDemo.ent"
 m_sName "#TK-Mission_DemoName"
 m_sAuthor "Triad Tactics"
 m_sDescription "#TK-Mission_DemoDescription"
 m_sGameMode "#TK-Mission_DemoGameMode"
 m_iPlayerCount 16
}